import type { MedicalSpecialtyProtocolDefinition } from "./types";

export const SPECIALTY_PROTOCOL_REGISTRY: MedicalSpecialtyProtocolDefinition[] = [
  {
    id: "cardiology",
    label: "Cardiologia",
    tone: "preciso, orientado a riesgo cardiovascular y tiempos de accion",
    reasoningStyle: "priorizar sindromes de alto riesgo, estabilidad hemodinamica y ECG/troponinas si aplica",
    protocolFocus: ["dolor toracico", "disnea", "sincope", "arritmias", "factores de riesgo cardiovascular"],
    redFlags: ["dolor toracico opresivo", "disnea severa", "sincope", "hipotension", "deficit neurologico asociado"],
    evidenceUse: "usar guias y evidencia solo si retrieval aporta fuentes; no inventar scores ni thresholds",
    structureHints: ["separar urgencia cardiovascular de diferenciales no cardiacos", "explicitar datos faltantes criticos"],
    patterns: [/\b(cardio|dolor toracico|dolor torácico|angina|infarto|arritmia|palpitaciones|sincope|síncope)\b/i],
  },
  {
    id: "psychiatry",
    label: "Psiquiatria",
    tone: "cuidadoso, no estigmatizante, orientado a seguridad y contencion profesional",
    reasoningStyle: "evaluar riesgo suicida/autolesivo, psicosis, mania, sustancias y soporte social",
    protocolFocus: ["riesgo suicida", "psicosis", "mania", "depresion", "ansiedad", "consumo de sustancias"],
    redFlags: ["ideacion suicida activa", "plan suicida", "psicosis aguda", "agitacion severa", "riesgo para terceros"],
    evidenceUse: "no atribuir causalidad psiquiatrica unica sin descartar causas medicas o sustancias",
    structureHints: ["diferenciar sintomas, riesgo y necesidad de evaluacion urgente", "evitar lenguaje determinista"],
    patterns: [/\b(psiquiatr|depresion|depresión|ansiedad|suicid|psicosis|bipolar|mania|autolesion|autolesión)\b/i],
  },
  {
    id: "pediatrics",
    label: "Pediatria",
    tone: "prudente, concreto y sensible a edad/peso/desarrollo",
    reasoningStyle: "considerar edad, peso, hidratacion, vacunacion, estado general y signos respiratorios",
    protocolFocus: ["edad", "peso", "hidratacion", "vacunas", "fiebre", "dificultad respiratoria"],
    redFlags: ["letargo", "dificultad respiratoria", "deshidratacion", "fiebre en lactante pequeno", "convulsion"],
    evidenceUse: "evitar dosis especificas si faltan peso, edad o funcion renal/hepatica",
    structureHints: ["separar conducta para lactantes, ninos y adolescentes cuando sea relevante"],
    patterns: [/\b(pediatr|niño|nino|niña|nina|lactante|bebe|bebé|adolescente|fiebre en menor)\b/i],
  },
  {
    id: "neurology",
    label: "Neurologia",
    tone: "sistematico, temporizado y orientado a deficit focal",
    reasoningStyle: "priorizar inicio temporal, focalidad, conciencia, convulsiones y signos de hipertension intracraneal",
    protocolFocus: ["ACV", "cefalea", "convulsiones", "deficit focal", "alteracion de conciencia"],
    redFlags: ["deficit neurologico focal", "cefalea brusca maxima", "convulsion persistente", "alteracion de conciencia"],
    evidenceUse: "no descartar eventos tiempo-dependientes sin evaluacion presencial e imagen si corresponde",
    structureHints: ["marcar ventana temporal y necesidad de evaluacion urgente si hay focalidad"],
    patterns: [/\b(neuro|acv|stroke|cefalea|convulsion|convulsión|deficit focal|déficit focal|parestesia|hemiparesia)\b/i],
  },
  {
    id: "endocrinology",
    label: "Endocrinologia",
    tone: "analitico, longitudinal y atento a medicacion/metabolismo",
    reasoningStyle: "ordenar sintomas, medicacion, adherencia, glucemias, electrolitos y comorbilidades",
    protocolFocus: ["diabetes", "tiroides", "glucemia", "adherencia", "complicaciones metabolicas"],
    redFlags: ["cetoacidosis sospechada", "hipoglucemia severa", "alteracion de conciencia", "deshidratacion severa"],
    evidenceUse: "no ajustar dosis complejas sin datos clinicos suficientes y seguimiento",
    structureHints: ["distinguir urgencia metabolica de control cronico"],
    patterns: [/\b(endo|diabetes|glucemia|hipoglucemia|hiperglucemia|tiroides|insulina|metabol)\b/i],
  },
  {
    id: "emergency",
    label: "Urgencias",
    tone: "directo, seguro y orientado a triage",
    reasoningStyle: "priorizar ABC, estabilidad, red flags y derivacion inmediata cuando corresponda",
    protocolFocus: ["triage", "ABC", "estabilidad", "signos vitales", "derivacion"],
    redFlags: ["shock", "disnea severa", "dolor toracico", "anafilaxia", "sepsis", "hemorragia", "ideacion suicida activa"],
    evidenceUse: "la seguridad inmediata prevalece sobre discusion extensa de evidencia",
    structureHints: ["abrir con prioridad de seguridad si hay riesgo vital"],
    patterns: [/\b(urgencia|emergencia|shock|anafilaxia|sepsis|hemorragia|riesgo vital|inestable)\b/i],
  },
  {
    id: "psychology",
    label: "Psicologia",
    tone: "empatico, colaborativo y no patologizante",
    reasoningStyle: "distinguir formulacion psicologica, factores mantenedores, recursos y limites clinicos",
    protocolFocus: ["contexto psicosocial", "funcionamiento", "afrontamiento", "red de apoyo", "riesgo"],
    redFlags: ["riesgo suicida", "violencia", "abuso", "psicosis", "deterioro funcional grave"],
    evidenceUse: "no reemplazar evaluacion psiquiatrica/medica si hay riesgo o sintomas graves",
    structureHints: ["separar hipotesis psicologicas de diagnosticos medicos"],
    patterns: [/\b(psicolog|terapia|duelo|estres|estrés|afrontamiento|conductual|cognitivo)\b/i],
  },
  {
    id: "general_medicine",
    label: "Medicina general",
    tone: "claro, prudente y orientado a atencion primaria",
    reasoningStyle: "diferencial amplio, estratificacion de riesgo y seguimiento practico",
    protocolFocus: ["motivo de consulta", "antecedentes", "medicacion", "signos vitales", "seguimiento"],
    redFlags: ["deterioro rapido", "fiebre persistente", "dolor intenso", "disnea", "alteracion de conciencia"],
    evidenceUse: "usar evidencia disponible sin inventar fuentes y explicitar incertidumbre",
    structureHints: ["ordenar datos faltantes y conducta escalonada"],
    patterns: [/\b(medicina general|clinica|clínica|consulta general|atencion primaria|atención primaria)\b/i],
  },
];
