"""Reproduce and diagnose deadlock patterns in slot booking locks.

Scenarios:
1. Inverse lock ordering (A: slot1->slot2, B: slot2->slot1) => expected deadlock risk
2. Ordered lock ordering (A: slot1->slot2, B: slot1->slot2) => expected no deadlock

Usage:
  e:/GSentinelHealthOS/.venv/Scripts/python.exe scripts/qa_detect_booking_deadlocks.py
"""

from __future__ import annotations

import os
import sys
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

import psycopg
from psycopg.errors import DeadlockDetected


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


def _dsn() -> str:
    raw = os.getenv("DATABASE_URL", "postgresql+psycopg://sentinel:sentinel_password@localhost:5432/sentinel_health")
    if raw.startswith("postgresql+psycopg://"):
        return "postgresql://" + raw[len("postgresql+psycopg://") :]
    if raw.startswith("postgresql+asyncpg://"):
        return "postgresql://" + raw[len("postgresql+asyncpg://") :]
    return raw


@dataclass
class TxResult:
    name: str
    backend_pid: int | None
    txid: int | None
    order: list[int]
    outcome: str
    detail: str


def _bootstrap(conn: psycopg.Connection[Any]) -> tuple[int, list[int]]:
    with conn.cursor() as cur:
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS doctors (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL,
                specialization VARCHAR(100),
                buffer_before_minutes INTEGER NOT NULL DEFAULT 30,
                buffer_after_minutes INTEGER NOT NULL DEFAULT 30
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS time_slots (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                doctor_id INTEGER NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
                start_time TIMESTAMPTZ NOT NULL,
                end_time TIMESTAMPTZ NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'available'
            )
            """
        )
        cur.execute("INSERT INTO doctors (name) VALUES ('Doctor Deadlock QA') RETURNING id")
        doctor_id = int(cur.fetchone()[0])

        base_utc = (datetime.now(timezone.utc) + timedelta(days=2)).replace(hour=14, minute=0, second=0, microsecond=0)
        slot_ids: list[int] = []
        for offset in (0, 15):
            cur.execute(
                """
                INSERT INTO time_slots (doctor_id, start_time, end_time, status)
                VALUES (%s, %s, %s, 'available')
                RETURNING id
                """,
                (doctor_id, base_utc + timedelta(minutes=offset), base_utc + timedelta(minutes=offset + 15)),
            )
            slot_ids.append(int(cur.fetchone()[0]))
    conn.commit()
    return doctor_id, slot_ids


def _cleanup(conn: psycopg.Connection[Any], doctor_id: int) -> None:
    with conn.cursor() as cur:
        cur.execute("DELETE FROM time_slots WHERE doctor_id = %s", (doctor_id,))
        cur.execute("DELETE FROM doctors WHERE id = %s", (doctor_id,))
    conn.commit()


def _lock_sequence(
    name: str,
    dsn: str,
    ordered_slot_ids: list[int],
    barrier: threading.Barrier | None,
    results: list[TxResult],
) -> None:
    conn = psycopg.connect(dsn, connect_timeout=5, autocommit=False)
    backend_pid: int | None = None
    txid: int | None = None
    try:
        with conn.cursor() as cur:
            cur.execute("SET lock_timeout = '5s'")
            cur.execute("SELECT pg_backend_pid(), txid_current()")
            meta = cur.fetchone()
            backend_pid = int(meta[0])
            txid = int(meta[1])

            print(f"[{name}] begin backend_pid={backend_pid} txid={txid} order={ordered_slot_ids}")

            cur.execute("SELECT id FROM time_slots WHERE id = %s FOR UPDATE", (ordered_slot_ids[0],))
            print(f"[{name}] locked first slot={ordered_slot_ids[0]}")

            if barrier is not None:
                barrier.wait(timeout=10)
            time.sleep(0.25)

            print(f"[{name}] waiting second slot={ordered_slot_ids[1]}")
            cur.execute("SELECT id FROM time_slots WHERE id = %s FOR UPDATE", (ordered_slot_ids[1],))
            print(f"[{name}] locked second slot={ordered_slot_ids[1]}")

        conn.commit()
        results.append(TxResult(name, backend_pid, txid, ordered_slot_ids, "ok", "completed without deadlock"))
    except DeadlockDetected as exc:
        conn.rollback()
        results.append(TxResult(name, backend_pid, txid, ordered_slot_ids, "deadlock", str(exc)))
        print(f"[{name}] DEADLOCK DETECTED: {exc}")
    except Exception as exc:  # noqa: BLE001
        conn.rollback()
        results.append(TxResult(name, backend_pid, txid, ordered_slot_ids, "error", str(exc)))
        print(f"[{name}] ERROR: {exc}")
    finally:
        conn.close()


def _run_pattern(label: str, dsn: str, order_a: list[int], order_b: list[int]) -> list[TxResult]:
    print(f"\n=== {label} ===")
    barrier = threading.Barrier(2) if order_a != order_b else None
    results: list[TxResult] = []

    thread_a = threading.Thread(target=_lock_sequence, args=("A", dsn, order_a, barrier, results), daemon=True)
    thread_b = threading.Thread(target=_lock_sequence, args=("B", dsn, order_b, barrier, results), daemon=True)

    thread_a.start()
    thread_b.start()
    thread_a.join()
    thread_b.join()

    print("Resultados:")
    for result in sorted(results, key=lambda item: item.name):
        print(
            f"tx={result.name} backend_pid={result.backend_pid} txid={result.txid} "
            f"order={result.order} outcome={result.outcome} detail={result.detail}"
        )
    return results


def main() -> int:
    dsn = _dsn()
    conn = psycopg.connect(dsn, connect_timeout=5, autocommit=False)
    doctor_id = 0
    try:
        doctor_id, slot_ids = _bootstrap(conn)
        slot_1, slot_2 = slot_ids[0], slot_ids[1]

        inverse_results = _run_pattern(
            "Patron inverso A(slot1->slot2) / B(slot2->slot1)",
            dsn,
            [slot_1, slot_2],
            [slot_2, slot_1],
        )

        ordered_results = _run_pattern(
            "Patron ordenado ASC para ambas transacciones",
            dsn,
            sorted([slot_1, slot_2]),
            sorted([slot_1, slot_2]),
        )

        inverse_deadlock = any(item.outcome == "deadlock" for item in inverse_results)
        ordered_deadlock = any(item.outcome == "deadlock" for item in ordered_results)

        print("\n=== Patron de deadlock ===")
        print(
            "A bloquea slot 1 y espera slot 2; B bloquea slot 2 y espera slot 1. "
            "Esto crea espera circular y PostgreSQL aborta una de las transacciones con deadlock detected."
        )

        print("\n=== Solucion concreta ===")
        print(
            "Ordenar siempre la adquisicion de locks por start_time ASC (y id ASC como desempate), "
            "de modo que todas las transacciones pidan los mismos rows en el mismo orden global."
        )

        print("\n=== Resumen ===")
        print(f"inverse_pattern_deadlock_detected: {inverse_deadlock}")
        print(f"ordered_pattern_deadlock_detected: {ordered_deadlock}")

        return 0 if inverse_deadlock and not ordered_deadlock else 1
    finally:
        if doctor_id:
            _cleanup(conn, doctor_id)
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
